mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=
spring:
  data:
    mongodb:
      uri: mongodb+srv://sa:R35rPvm0XFgR8dIh@walter.iyabt.mongodb.net/bootcamp?retryWrites=true&w=majority
server:
  port: 8040